[package]
name = "game_quad"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad  = {version = "0.4.13", features = ["audio"]}
rand = "0.9.0"
bincode  = "1.3"
serde = { version = "1.0", features = ["derive"] }